name = "kleague-toto-predictor"
main = "src/index.ts"
compatibility_date = "2025-07-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "kleague-toto-db"
database_id = "3a5fc8d6-f831-4a4c-9e16-90223cc56467"

[[kv_namespaces]]
binding = "KV"
id = "4eddcce52bd645d3ac728fb93e3b4892"

[triggers]
crons = ["0 */3 * * *", "0 */6 * * *"]

[vars]
ENVIRONMENT = "production"
